### ISSUE TITLE
Not parsing BOAR's head Atlas.

### ISSUE THREAD

**Issue by Alaric-VISIGOTH** [lisongmechlab/lsml#145]
As above.

Alaric

**Comment by Alaric-VISIGOTH** [comment]
All the Atlas I see are XL360 top engine Boar's head can have a 400xl 
none of these have that.

**Comment by LiSongMWO** [comment]
I have no idea what you are on about... please post steps to reproduce
according to my previous comment.

**Comment by Alaric-VISIGOTH** [comment]
Nothing to reproduce, your program is missing New Atlas Boar's head..

**Comment by Alaric-VISIGOTH** [comment]
I'll try re-installing, definitely not there for me. Patched game files 
as well..

Did you see the screenshot?

AV

**Comment by Alaric-VISIGOTH** [comment]
Li Song, I just un-installed and re-installed your program it is not 
showing me
the BOAR's head mech. Game files are patched, I have attached screenshot.

The contents of lsml_settings.xml are below.

AV

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<comment>Written by LSML</comment>
<entry key="garagefile">D:\Users (Atlantis-2K)\Documents\LiSong 
Mechs.xml</entry>
<entry key="gamedir">H:\Users (Live Games)\Symbolics F-Drive\MechWarrior 
Online</entry>
</properties>

**Comment by LiSongMWO** [comment]
(No screenshot received)

You are certain `H:\Users (Live Games)\Symbolics F-Drive\MechWarrior Online`
points to the correct install (not your PTS for example)?

Have you extracted any of the game files from the .PAK files? Specifically,
make sure that you do not have any of the extracted files in your `Game`
directory. I think Zero ran into this, he had some of the data files
extracted in the game folder and they were parsed instead of the actual
game files.

**Comment by Alaric-VISIGOTH** [comment]
That's odd I attached a screenshot on a few of these messages, github 
must be stripping them.

I only have one install of MWO, not using the Beta right now.
My PAK files are fine, no extracted files.
I am Cc your other address so you can see attachments.

**Comment by Alaric-VISIGOTH** [comment]
Here is a activity log, you will need 
http://technet.microsoft.com/en-us/sysinternals/bb896645 to view..

Later
AV

**Comment by Alaric-VISIGOTH** [comment]
That's fine, we'll arrange a time.

AV
