### ISSUE TITLE
Designs comparison table

### ISSUE THREAD

**Issue by vetall812** [lisongmechlab/lsml#239]
Would you also add table that allow to compare two designs:
we have to select two mechs: mechA and mechB that it fill the table:
-------------> range (100 meters per column)
| damage done by mechA
|
v time (5 sec per row)

and let damage will be green if MechA damage is greater than damage made by MechB at this range at this time. And red otherwise. (Black/gray/neutral - if equal).

**Comment by LiSongMWO** [comment]
I don't think I'm ever going to get the time to do this so I'm closing this as won't fix in an effort to clean up the issue tracker a bit.
