### ISSUE TITLE
Crit stats not showing for fixed equipment

### ISSUE THREAD

**Issue by LiSongMWO** [lisongmechlab/lsml#510]
Actually they are not shown for disabled items, that's what's happening.

**Comment by EmilyBjoerk** [comment]
This is caused by:
https://bugs.openjdk.java.net/browse/JDK-8090379

Postponing workaround/fix for 2.1.

**Comment by LiSongMWO** [comment]
Doesn't seem like the JFX bug will get fixed. We can work around this by wrapping items in a stack pane, ugly as it is.

**Comment by LiSongMWO** [comment]
Not worth the effort to fix this.
