### ISSUE TITLE
The "Auto-detect game installation" feature could be optimized

### ISSUE THREAD

**Issue by VioletGiraffe** [lisongmechlab/lsml#575]
The search seems too straightforward. Realistically, do you really need to scan _all_ the suspect folders in-depth? Wouldn't it make sense to limit the search depth at 3-4? And if the user hid the game really well, make them point it out instead of scanning the whole 2 TB HDD.

P. S. Look for Steam as well as MWO folder because Steam itself keeps game installations several folders deep.
P. P. S. You could probably look for it in the registry, too, that should be even faster.

**Comment by EmilyBjoerk** [comment]
Limiting the search depth means the algorithm might miss the install on some systems (do not underestimate how much people like organising things in folders!) and I kind of like the fact that it will always succeed if there is a valid game install. 

LSML works on Mac and Linux too and looking in the registry would break this while the current algorithm works for Mac and Linux. Even works when some one has copied the game install or moved it manually and the registry entry doesn't exist or is faulty. So using the registry isn't really an option (and it's tricky in Java).

At any rate this is something that a user does very rarely and for most people who install at the default location it is instantaneous as these are checked before anything else. Making it smoother isn't a priority for me. If you would like to improve it by yourself, I accept patches. See [How to Contribute](https://github.com/EmilyBjoerk/lsml/wiki/How-to-Contribute) for more information.

**Comment by VioletGiraffe** [comment]
Will always succeed given unlimited time - sure :)
A compromise could be not prohibiting the exhaustive search, but simply checking first with a faster method and only using full search as a last resort.
It's true that it's not something people have to do often, but consider that it's one of the first (if not the very first) experiences of a new LSML user.

Also, I don't believe MWO is available on Linux or Mac.

**Comment by EmilyBjoerk** [comment]
It might be possible to change from a depth first to a breadth first traversal. At any rate it's not a priority right now as my time is very limited. 

MWO doesn't need be usable, just data files readable. People who dual boot can easily access MWO files from Linux or Mac using LSML.

**Comment by VioletGiraffe** [comment]
I get that you're busy and this is a very low priority thing. I'm merely replying to your points, not trying to convince you to drop whatever you're doing and do this :)

Thanks for however much time you're managing to put into this project.

**Comment by LiSongMWO** [comment]
Closing this as the auto-detect feature has been removed.
