### ISSUE TITLE
Ability to filter out movement quirks

### ISSUE THREAD

**Issue by astro-hemlow** [lisongmechlab/lsml#588]
The list of quirks can be rather long on some mechs and sometimes you just want to glance at weapons quirks while building. It would be nice with an option to filter out movement quirks just like armor and structure quirks can be filtered.

**Comment by LiSongMWO** [comment]
The request is for filtering out movement quirks but the use-case is stated as only looking at weapon quirks. I'm interpreting this as not filtering out the movement quirks, but only showing weapon related quirks instead.
