### ISSUE TITLE
Cloud storage-hosted garage

### ISSUE THREAD

**Issue by VioletGiraffe** [lisongmechlab/lsml#645]
I'm theorycrafting my builds on at least two PCs in different locations. Would be great if I had access to all my builds from any place.

You might say I can just sync the garage .xml file using external tools, but that requires desktop apps and they're all terrible; it's hard to make them do exactly what I want (if at all possible).

**Comment by EmilyBjoerk** [comment]
Thanks for the suggestion. Creating a cloud storage is a massive job which
requires constant maintenance, backups and ongoing operating expenses. I do
not have the money or time to do this at this time.

Please consider supporting the Patreon campaign. With enough support I
could put more time into lsml. https://www.patreon.com/LSML

In the mean while you can put your garage file in Dropbox or Google Drive.
And have it shared across all of your computers.

Thank you again for taking the time to post the suggestion. I will close
this issue as won't fix for now. If conditions change or some one
volunteers to do this out of their own time and money I will reopen the
issue.

**Comment by VioletGiraffe** [comment]
I didn't mean hosting your own cloud storage, I mean connecting to an existing account. E. g. I log into my Google Drive and the program puts the garage file there automatically. I've seen a couple not-so-large programs do that. There probably are open-source Java libraries for that, too.

And as I said, all the desktop apps are awful to the point of being unusable for my tasks - I've tried Google Drive, Dropbox, Microsoft OneDrive, Yandex Disk. I'm only saying this to underline that to me it makes perfect sense including this functionality in the application. Some other open-source game-related programs that I use do it, and it's very convenient.

**Comment by EmilyBjoerk** [comment]
I'm not opposed to the feature and if some one else wants to contribute the code under GPLv3 I'm more than happy to accept it provided it meets reasonable quality standards.

But considering that there exists an easy and obvious way to get it to work for any cloud service using their respective desktop clients, there are better things to spend my LSML dev time on. Personally I use Google Drive for syncing garage and other programs' data files between computers without any issues. I don't know why you call the desktop clients awful, they do their job and at least Google Drive stays out of my hair.

**Comment by VioletGiraffe** [comment]
Great! I might want to implement it myself when I gather all my courage together. I never did desktop Java development, but I do some Android Java stuff. I'm curious to see what it would take to compile LSML from source, and if I can do that, I'd love to be a contributor, too :)

There's official Java API for [Dropbox](https://www.dropbox.com/developers/documentation/java#tutorial) and for [Google Drive](https://developers.google.com/api-client-library/java/apis/drive/v2) (but not for Onedrive - go C# or go home, says Microsoft).

**Comment by EmilyBjoerk** [comment]
There is a developer manual under the wiki:
https://github.com/EmilyBjoerk/lsml/wiki

It may be slightly out of date but for most parts it is still accurate. You can create issues towards the wiki too if you find it lacking. I'll try to write up a "howto" page for contributors.

**Comment by LiSongMWO** [comment]
Seeing that this bug has been open for 5 years without any upvotes or contributions. I'm going to consider this as a nice to have that most likely will not get implemented. For that reason I'm closing this as `won't fix` in an effort to clean up the list of open issues a bit.
