### ISSUE TITLE
Verify computations of MRM

### ISSUE THREAD

**Issue by LiSongMWO** [lisongmechlab/lsml#687]
Make sure that the way we compute DPS and other stats for MRMs is correct.

**Comment by VioletGiraffe** [comment]
I wonder if they fixed Testing Grounds to account for mech skills. That would make verifying things that much easier.

**Comment by EmilyBjoerk** [comment]
My default stance wrt testing grounds is that any results from testing
grounds are doubted until proven correct on a live server.

Den 26 juli 2017 12:23 skrev "Violet Giraffe" <notifications@github.com>:

**Comment by Tyler799** [comment]
Testing grounds is an inaccurate place to do any real testing. It often has issues like values not being applied correctly, or % chances not rolling right. (IE, UAC jams)

Generally the best place for testing is a private lobby or a live match.

**Comment by Tyler799** [comment]
I meant to mention: I'm not experienced with coding, but if you need a hand with anything else (testing the program itself, or helping you run tests in a private lobby) I'm 100% always at your disposal any time. I love LSML and want to help out even if I can't provide code.

**Comment by LiSongMWO** [comment]
Ok I finally, after 5 years found the time to check this. And it turns out that there's a wider issue with how missile weapon spread is calculated. I'll create a follow-up and close this investigation.
