### ISSUE TITLE
Verify stats of C-ATM

### ISSUE THREAD

**Issue by LiSongMWO** [lisongmechlab/lsml#689]
I have no idea how ATM's function on account of not having played for ages. We need to verify if whatever LSML does for ATMs is the "right thing".

**Comment by EmilyBjoerk** [comment]
```
<WeaponStats Health="3.5" slots="2" type="Missile" projectileclass="javelin" numFiring="3" damage="2.0" heatdamage="0" heatpenalty="3.1" minheatpenaltylevel="5" impulse="0.15" heatPenaltyID="6" heat="2.5" cooldown="5.0" ammoType="ClanATMAmmo" ammoPerShot="3" tons="1.5" duration="0.0" lifetime="15.0" speed="200" volleydelay="0.05" volleysize="1" peakdist="0.6" peaktime="-0.333" minheight="20" maxheight="45" uselock="1" trackingstrength="2.0" radius="0.05" formation_speed="2.5" formation_size="0.1" formation_size_per_index="0.01" spread="3.0" falloffexponent="2" critDamMult="1.0" alwaysHasArtemis="1" useArtemisUpgradeBonus="0" />
```

**Comment by Tyler799** [comment]
I don't know how I could help you test if LSML does the right thing, but I can tell you the ranges on ATMs:

* Min range: 120m
* 3 damage: 120m -> 270m
* 2 damage: 270m -> 540m
* 1 damage: 540m -> 1100m

However, the range graph on MWO seems to suggest the damage change isn't _quite_ instant from the brackets. So the border of the 3->2 damage range is a little fuzzy. It changes in the span of a few meters from one to the other, not instantly.

As for anything else you want to know, just ask! 

Oh, and Artemis being on/off doesn't do anything, like with IS MRMs or Streaks

**Comment by NavidA1** [comment]
**Min range:** 120m
**3 damage:** 120m to 270m
**linear fall off from 3 to 2 damage:** 270m to 320m
**2 damage:** 320m to 500m
**linear fall off from 2 to 1 damage:** 500m to 550m
**1 damage:** 550m to 1100

* damage per missile

**Comment by EmilyBjoerk** [comment]
The ranges and damage values are already extracted from the data file
automatically. What I'm looking for here is testing results from lobby. For
example shoot one shot at a certain distance and then end the match and
look at damage done at end of match.

**Comment by sestrand** [comment]
Do you still need some research here? Are you thinking of implementing some more range charts or data in LSML?  I assume that you are also looking to see if any rounds actually miss?

**Comment by LiSongMWO** [comment]
I've not used these weapons so my questions are phrased around damage fall-off and spread etc. Quickly checking right now it seems like the range affects on damage are correctly accounted for. I don't know if there's any amount of spread that should be included like LSML does for SRMs and LBX type weapons. 

Basically, the request here is to look at what LSML produces and verify that the behaviour in game is the same.

**Comment by LiSongMWO** [comment]
Ok so there is some type of spread out and then converge on the target behaviour here. I'm not sure how to model this or if it's even necessary to model. I'm leaning towards it being OK as it is so I will close this until someone complains :)

**Comment by sestrand** [comment]
Makes sense to me.  I will try to collect some test data, jsut to see how much hits from what ranges.  but I will not put a big rush on it.

**Comment by sestrand** [comment]
they do not all hit, at least visually.  so data will be needed.  there does seem to be some spread, but I cannot tell if it is a steady spread or some weird equation.

**Comment by LiSongMWO** [comment]
Let's move this discussion no #789 that I filed to collate all the various spread related issues.
