### ISSUE TITLE
Some additional mobility information that can be added to mech statistics panel

### ISSUE THREAD

**Issue by NavidA1** [lisongmechlab/lsml#738]
here are the formulas for acceleration , deceleration , 0 to 100% time, 100 to 0% time, and twist and turn stats... which can be added to mech stats panel as additional pieces of information.
They are tested and validated in game using video recordings under various conditions and settings

https://i.imgur.com/Y0beNu7.jpg
also... the info on ingame UI graph:
https://i.imgur.com/xUyvX9B.png

also for reference, here is how they were when mobility was sync'd with engine rating:
https://i.imgur.com/cbqHcXD.jpg

**Comment by EmilyBjoerk** [comment]
Thanks, I found these years ago but decided the graphs weren't useful. 

How would you use these graphs to improve your loadout or gameplay?

**Comment by NavidA1** [comment]
The graphs are not useful in optimizing builds.

The only useful information among those are the accel/decel times I think.

**Comment by EmilyBjoerk** [comment]
Do you mean the 0-100 and 100-0 times?

**Comment by NavidA1** [comment]
Yes. 
I should say though that they don't play a part in how you build your mech. Just extra information.

**Comment by LiSongMWO** [comment]
Given how cluttered the movement panel is already, and that these metrics don't impact how you build and is just "curiosity" and my limited time and few contributors to the project. I don't think that this will ever get done so I'm closing this as won't fix.
