### ISSUE TITLE
History rewritten

### ISSUE THREAD

**Issue by LiSongMWO** [lisongmechlab/lsml#744]
I had to rewrite history due to my email address being mined by recruiters.

@Alaric-VISIGOTH ~@Zesaric~ @Troopie ~@Krivvan~ ~@jmgao~ ~@Dauphni~ @BanditFly @anonymous555 

You have all forked the repo. I kindly ask that you delete and remake your forks (if you want to keep them).

**Comment by jmgao** [comment]
Done.

**Comment by Zesaric** [comment]
Also done!
