### ISSUE TITLE
IS CASE in arms and legs after 20/04/2021 patch

### ISSUE THREAD

**Issue by RosariusAU** [lisongmechlab/lsml#745]
The most recent MWO patch changed IS CASE so that it now costs zero tonnage and can be equipped in the arms and legs of the mech. Li Song Mechlab has been able to capture the tonnage change correctly from the game files, but I am unable to equip CASE in arms and legs

A minor bug, but a bug nonetheless.

**Comment by LiSongMWO** [comment]
Thanks for the report, I'll take a look. I bit busy these days tho so it might be a moment.
