### ISSUE TITLE
RAC DPS being calculated incorrectly

### ISSUE THREAD

**Issue by NonceCents** [lisongmechlab/lsml#746]
**LSML version:** 2.0.11
**Screen resolution:** 2560x1440
**Java version:** 8u201

**Steps to reproduce issue:**
1. Open LSML
2. Open the Weapons panel
3. Look at the ROTARY AC/2 and the ROTARY AC/5

**Actual result:**
Observe that the cooldown for RAC weapons are listed as .28 seconds.

**Expected result:**
A RAC2 does .9 damage 7.275 times per second, or once every 0.1374570446735395 seconds. This can be confirmed in-game as well as in the database.xml:

```
    <ballisticweapon id="1380" name="ROTARY AC/2" shortName="ROTARY AC/2" description="A large, rapid-fire autocannon. Can jam if fired for too long." mwoKey="RotaryAutoCannon2" mwoId="1058" faction="INNERSPHERE" slots="3" tons="8.0" hardpointType="BALLISTIC" health="10.0" roundsPerShot="1" damagePerProjectile="0.9" projectilesPerRound="1" ghostHeatGroupId="11" ghostHeatMultiplier="5.0" volleyDelay="0.0" impulse="0.03" ammoTypeId="RotaryAC2Ammo" oneShot="false" shotsduringcooldown="0" chargeTime="0.0" rampUpTime="0.75" rampDownTime="2.0" jamRampUpTime="8.0" rampDownDelay="0.3">
      <heat id="1381" specifier="heat" value="2.0" selectors="isrotaryautocannon,rotaryautocannon2,largeweapon,key#rotaryautocannon2,isrotaryautocannon2,ballistic,rotaryautocannon"/>
      <coolDown id="1382" specifier="cooldown" value="0.1374570446735395" selectors="isrotaryautocannon,rotaryautocannon2,largeweapon,key#rotaryautocannon2,isrotaryautocannon2,ballistic,rotaryautocannon"/>
```

A RAC5 does 1.5 damage 7.275 times per second, or once every 0.1374570446735395 seconds. This can be confirmed in-game as well as in the database.xml:

```
    <ballisticweapon id="1397" name="ROTARY AC/5" shortName="ROTARY AC/5" description="A large, rapid-fire autocannon. Can jam if fired for too long." mwoKey="RotaryAutoCannon5" mwoId="1059" faction="INNERSPHERE" slots="6" tons="10.0" hardpointType="BALLISTIC" health="15.0" roundsPerShot="1" damagePerProjectile="1.5" projectilesPerRound="1" ghostHeatGroupId="11" ghostHeatMultiplier="6.0" volleyDelay="0.0" impulse="0.03" ammoTypeId="RotaryAC5Ammo" oneShot="false" shotsduringcooldown="0" chargeTime="0.0" rampUpTime="1.0" rampDownTime="2.0" jamRampUpTime="8.0" rampDownDelay="0.3">
      <heat id="1398" specifier="heat" value="3.25" selectors="isrotaryautocannon,largeweapon,ballistic,rotaryautocannon,isrotaryautocannon5,key#rotaryautocannon5,rotaryautocannon5"/>
      <coolDown id="1399" specifier="cooldown" value="0.1374570446735395" 
```

Both RAC weapons should have the cooldown listed as roughly .14, or half of what is listed in LSML.

**Comment by LiSongMWO** [comment]
In LSML the "MaxDPS" means what the pilot would get when holding down the trigger for a long time, assuming heat is not an issue. And "SustainedDPS" is the same but instead assuming that the pilot will always use the most heat efficient weapon choice for the specifed ranges, i.e. the maximum dps that your heatsinks can sustain for a perfect pilot.

To this end LSML uses statistical models to compute the true maximum DPS of a weapon over a long time assuming the pilot holds down the trigger, for RAC and UAC type weapons this DPS includes the chance that the weapon will jam when firing continuously and how long it takes for the RAC to spin up and down between jams. And for gauss rifles this includes the charge time etc... For this reason the actual DPS that you will observe with a RAC on a long time frame is the value that LSML shows you currently which indicates that for sustained fights, it's not a great weapon for DPS.

Or in other words: What you have computed in your post is the maximum theoretical peak DPS, what LSML shows you is the expected maximum DPS over a long time frame including spin-up/down and jams chance.

The code to compute the effective number of rounds per second for these types of weapons is here:

https://github.com/lisongmechlab/lsml/blob/177597327beafca1f6e5b4acc1f9d9aedec4808e/src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java#L123

I hope this answers your question, I don't have reason to believe that LSML is doing anything wrong in this case and that it's a confusion between maximum peak and maximum average.

**Comment by NonceCents** [comment]
> In LSML the "MaxDPS" means what the pilot would get when holding down the trigger for a long time, assuming heat is not an issue. And "SustainedDPS" is the same but instead assuming that the pilot will always use the most heat efficient weapon choice for the specifed ranges, i.e. the maximum dps that your heatsinks can sustain for a perfect pilot.
> 
> To this end LSML uses statistical models to compute the true maximum DPS of a weapon over a long time assuming the pilot holds down the trigger, for RAC and UAC type weapons this DPS includes the chance that the weapon will jam when firing continuously and how long it takes for the RAC to spin up and down between jams. And for gauss rifles this includes the charge time etc... For this reason the actual DPS that you will observe with a RAC on a long time frame is the value that LSML shows you currently which indicates that for sustained fights, it's not a great weapon for DPS.
> 
> Or in other words: What you have computed in your post is the maximum theoretical peak DPS, what LSML shows you is the expected maximum DPS over a long time frame including spin-up/down and jams chance.
> 
> The code to compute the effective number of rounds per second for these types of weapons is here:
> 
> https://github.com/lisongmechlab/lsml/blob/177597327beafca1f6e5b4acc1f9d9aedec4808e/src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java#L123
> 
> I hope this answers your question, I don't have reason to believe that LSML is doing anything wrong in this case and that it's a confusion between maximum peak and maximum average.

While I can appreciate this, it's still incorrect when calculating things like burst DPS values which are a value lower than the amount of time it takes to fill the jam bar. 

I believe it's important for LSML to display the correct actual value for RAC weapon cooldown between fired rounds as well as the true DPS the weapon achieves when fired normally before it even has the opportunity to jam. Simply put, the cooldown values LSML displays are not accurate; the weapon does not fire every .28 seconds.

It would make more sense to me for RAC weapons to display their unjammed DPS as Max DPS and their jammed / heat-restricted values as Sustained DPS, and for the cooldown values in the LSML Weapons table to be accurate to the actual fire rate of the weapon.

I see why you wrote it the way you did to account for UAC jamming, but RACs operate fairly differently.

**Comment by LiSongMWO** [comment]
So the burst calculations are different and don't use the DPS calculation in that way, but rather compute the likely number of shots you'd fire within that time window. So if the weapon had a cooldown of 5.1 seconds and did 10 damage, in a 5 second burst window the burst damage is exactly 10 damage. If the burst window is 5.2 seconds, then the burst damage is 20 for that weapon. So it does a discrete time simulation of sorts to figure out exactly how many shots you are likely get off (in the presence of jams etc). 

Note that LSML doesn't display burst **DPS** it displays burst **damage**. This is intended for hit and run type scenarios where you might want optimize your burst to be able to drop an assault in the rear CT in X seconds before running off to cool down.

For RAC's it uses the correct "raw" time between shots (not the long time average one) but it assumes that you spin up your weapon before engaging. But there's a bug where it assumes that the weapon can jam from the moment you start shooting, I can fix that.

Sans the above bug, the burst damage is correct and as you expect. Like I said it's not based on the expected maximum DPS values but rather an averaged simulation of individual shots over a time frame. You're giving LSML too little credit ;)

See:
https://github.com/lisongmechlab/lsml/blob/177597327beafca1f6e5b4acc1f9d9aedec4808e/src/main/java/org/lisoft/lsml/model/metrics/helpers/DoubleFireBurstSignal.java

and 
https://github.com/lisongmechlab/lsml/blob/177597327beafca1f6e5b4acc1f9d9aedec4808e/src/main/java/org/lisoft/lsml/model/metrics/BurstDamageOverTime.java

The philosophy of LSML has always been to show you the true expected, average behaviour of weapons and your builds in the long run, and as accurately as possible; from that point LSML is displaying the correct value for both DPS and cooldown for RACs. However the values shown are obviously not what you expected, but they are still correct and working as intended. From that point of view that this is not a bug but rather a request of an enhancement of the presentation.

The MaxDPS is correct from it's definition of "hold down button" DPS and the cooldown values shown in the weapons table are also correct in respect to the tooltip and LSML philosophy. The weapon does fire on average every .28 seconds. If cooldown was shown as the raw value in this table (like you propose), then the computation `Dmg/CD`  would not match up with the `DPS` column and that'd be even more confusing.

I do not want to treat RAC weapons differently than other weapons like Gauss (that include charge time) and UAC that include jam chances for these tables. Everything needs to be treated consistently.

So in that sense what this issue sounds like to me is two things:

1. Fix the bug to include the "jam free" time in RAC burst computations.
2. You want to relabel things in the UI and add additional columns to distinguish Peak DPS from Expected DPS and Sustained DPS, as well as expected time between shots and nominal time between shots in the weapons table.

The first one I can do, the second one I cannot promise as LSML is in maintenance mode for me and I don't think I'll have to time to do that as it's a larger amount of work. I'll happily accept patches.

**Comment by NonceCents** [comment]
```
Fix the bug to include the "jam free" time in RAC burst computations.
You want to relabel things in the UI and add additional columns to distinguish Peak DPS from Expected DPS and Sustained DPS, as well as expected time between shots and nominal time between shots in the weapons table.
```

In this case, I'm just a user and expressing how the data appears to be displayed includes assumptions that aren't expressed anywhere. I tend to expect that a cooldown value in a table is accurate to the actual per-shot cooldown in-game without arbitrary jam calculations being included, and that a burst DPS value would not include jam calculations which don't apply before a weapon is even able to jam.

So how it's handled becomes a matter of opinions from your userbase (and whether or not anyone other than nerds like me actually care) in how RAC damage is displayed.

**Comment by LiSongMWO** [comment]
I'm not sure what you're saying? Are you arguing for arguing's sake or are you opposed to my proposed fix?

**Comment by NonceCents** [comment]
Not at all, perhaps you misunderstand. 

I support your proposed fix in Proposal 1, but Proposal 2 would require feedback from the rest of your userbase, I assume. I don't deign to speak for what everyone else wants to see in terms of UI.

**Comment by sestrand** [comment]
RAC heat seems off to me as well.  Mechs running RACS do not heat up as fast as this tool predicts.  (other tools over predict RAC heat also)  and I think that is related to how the xml files report rac alpha heat.  as far as I can determine, RAC heat per 'volley' is based off of a 3 second firing 'volley' (plus one second spin up) which also consumes (3/.14) 21.825 rounds.  giving the weapon 8 volley's per ton for the rac5 and 16 volley's per ton for the rac2 ammo.  (as they have the same ROF of 1 rounds per .14 secs).  I could be a bit off on my own observations/analysis, I have not dug deeply into the xml files to see what data might be the better match.  But testing and some math lead me to this conclusion and it maps pretty well in my own tools (spreadhseets) for building mechs to what happens in game.

great tool BTW, other than the latest parse error and the RAC heat calculation.  you could come on back, the water is fine right now.  game has decent participation and the open play is challenging.

**Comment by LiSongMWO** [comment]
@sestrand the gold standard here is testing in a lobby game on official servers. I do not consider results from proving grounds to be reliable as there have been issues in the past where the behaviour on proving grounds and the live servers differed. If you want to do the science & math (please capture video so I can peer review) I'm happy to change the computation model for RACs to be more accurate within the model of LSML's computations (see earlier in thread). 

I appreciate the feedback and the heads up on the state of the game, but personally I'm "over" F2P games they don't spark joy for me any more. Coupled with work and other hobbies I'm struggling to find the time and motivation to work on LSML as I'm essentially giving away my free time for no gain to myself and I don't actually know how many people are actively using it... I should write a post somewhere... 

I'll try to fix the parse errors, IS case and parts if not all of this bug soon (tm) but life is kicking a girl lying down so don't wait up...

**Comment by sestrand** [comment]
i'll see if I can determine some more hard math. and use the live servers.
I did not realize there was a difference.  This tool and others report RACs
with very high heat rates. I think it is related to how heat is presented
by Piranha, but I'll try to research it better.  by limiting the "duration"
to 3 seconds in my own spreadsheets, the heat values match my use in game
(albeit mostly timing from the proving ground, in game can be a bit
to busy.). I'll try to capture video. Also , I have not dug into the games
source files to get better math just going by patch notes.

would the solaris tournament area be valid or is there a difference in
there from the multiplayer? (I can probably get good data from there
without letting down my team)

also sorry life is rough for you lately.  I just found this tool fairly
recently, I have liked this one more than smurfy and mechdb. I wish I had
found it sooner.  also smurfy is no longer being maintained either. thanks
for your time... designing and virtually testing mech ideas is probably 1/2
the fun of MWO for me...  I dont think you have a huge following, but
thanks for what you've done for those of us that found this thing.

I have decided that there really is no diff between F2P and any other way
of monetizing... they all show up as beta (whether full priced or free to
play with lots of micro)  and we all hope they can keep enough momentum of
users to give the developers incentive to fix it before the fan base
collapses.

**Comment by sestrand** [comment]
Again thanks for your time on this tool

ok, some easy math.  (I hope)

In game, RAC5 heat is 3.25/s, RAC2 is 2/s, stated in patch notes, in the MECHLAB and from the code found by NonceCents.  heat begins after the 1 second spin up and continues to build until you release the trigger.  Ghost heat is unchanged for quite some time.

LSML reports heat as 11.59 for the RAC5.   then that error is propagated to a much larger heat for the bursts.

for a 5s burst, a single RAC2 should add 4 seconds of heat at 2/s for a total of 8.   concurrently, heat is being shed at whatever the mech is able to shed per second (1.4 heat units per second for a mech with 10 single sinks).

 what are you defining as a single volley for RACs for the alpha? I offer a recommendation of a 3 sec burst as the alpha.  for RAC2 that is 4 heat and RAC5 is 7.5 heat.   Then the burst calculation feature would use the time (minus a second of spin) to get to the actual heat.  

I think if that were implemented, the overestimation of heat would be completely cleared up.  plus, the source values can come from the code you read already.

the rac does not jam before 8 seconds.  so the smaller burst value should not include that factor. beyond that, you could include it as part of the damage calc.  but realistically, once you hit the heat limits you are pretty much done generating damage as well...

**Comment by sestrand** [comment]
Did a little more math... to match your tool to the firepower rating in game... the alpha should be 5 seconds of firing (plus one second of spin up) or a 6 second burst. The 5s burst would be lower than alpha for a RAC based mech, as it would have 1 sec spin up then 4 seconds of damage).

in game a single rac5 has a firepower of 54.6damage .  Which is 5 seconds * 1.5 dmg per round / 0.1374570446735395 seconds per round.

**Comment by LiSongMWO** [comment]
I haven't had time to look at your numbers yet but we need to focus this around what's in the game data files. LSML parses all the values from there and I do not enter values manually.

The game files have the following:

```
  <Weapon id="1059" name="RotaryAutoCannon5" HardpointAliases="Ballistic,LargeWeapon,RotaryAutoCannon,RotaryAutoCannon5,ISRotaryAutoCannon,ISRotaryAutoCannon5" faction="InnerSphere">
    <Loc nameTag="@RAC5" descTag="@RAC5_desc" iconTag="StoreIcons\RotaryAutoCannon5.png"/>
    <WeaponStats Health="15" slots="6" type="Ballistic" projectileclass="bullet" numFiring="1" damage="1.5" heatdamage="0" heatpenalty="6.0" heatPenaltyID="11" minheatpenaltylevel="3" impulse="0.03" heat="3.25" cooldown="0" ammoType="RotaryAC5Ammo" ammoPerShot="1" tons="10" duration="-1" lifetime="10.0" speed="1300" volleydelay="0" rof="7.275" spread="0.19" gravity="0,0,-9.8" maxDepth="10.0" rampUpTime="1.0" rampDownTime="2.0" jamRampUpTime="8.0" jamRampDownTime="9.5" RampDownDelay="0.3" JammingChance="0.037" JammedTime="10" MinReactivationTIme="0.15"/>
    <Ranges>
      <Range start="0" damageModifier="1.0" interpolationToNextRange="linear"/>
      <Range start="450" damageModifier="1.0" interpolationToNextRange="linear"/>
      <Range start="900" damageModifier="0" interpolationToNextRange="linear"/>
    </Ranges>
  </Weapon>
```

or with the relevant numbers formatted more readably:

```
numFiring="1"
damage="1.5"
heatpenalty="6.0" 
heatPenaltyID="11" 
minheatpenaltylevel="3" 
heat="3.25"
cooldown="0"
ammoType="RotaryAC5Ammo"
ammoPerShot="1" 
rof="7.275"
spread="0.19"
rampUpTime="1.0"
rampDownTime="2.0"
jamRampUpTime="8.0"
jamRampDownTime="9.5"
RampDownDelay="0.3"
JammingChance="0.037"
JammedTime="10"
MinReactivationTIme="0.15"
```
LSML interprets the `heat` value to be per shot for ballistics weapons as has been the case for all other ballistics. Is that supposed to be treated differently for RAC? Why PGI? Why can you not be consistent?... *sigh*

**Comment by sestrand** [comment]
Flamer heat and damage works the same way, if that helps.  I suspect, if
MGs had heat, MGs would work like that too.

for a single rac5 in the mechlab, in game:
heat is listed at 3.25/s and the damage is listed as 10.913/s.  10.913
equates to 1.5 * 7.275. so I have to assume that the heat per shot is
calculated to be 3.25 / 7.275 or 0.4467 heat units per shot.

the firepower calculation in game is 54.6 ... which for most weapons is
based on a single trigger pull... in this case for RACs equates to a 6
second trigger pull (1 second spin up and 5 seconds of continuous burst).
I assume that 5second of firing was selected arbitrarily by PGI.

flamers have no spin up, but the firepower metric in game is also a 5
second long burst.
MGs have similar damage and firepower calculations to the RACs

**Comment by sestrand** [comment]
I would like to add.  heat is not generated during spin up.  if that helps
you.

**Comment by LiSongMWO** [comment]
I will fix the heat but the damage values are still correct. 
LSML shows damage output in realistic ways. There is the "alpha" damage which is what you look at for "peek and shoot" or "pop-tart" like engagements. There's sustained DPS as you would use in a longer brawl engagement, there's Max DPS as a reference and what you can output if you hit override shutdown and go ham, and finally there's the burst calculation to analyse specific engagement lengths. As far as I know, all of these still compute the correct damage value for each intended use case. 

Matching values with what is shown in the in-game mechlab, or other tools has never been a goal of LSML. The goal has always been to show you what you will statistically get in-combat, under the presented scenarios... For this reason I will likely not change the way damage is displayed for RAC weapons to match the 5 second burst in the in-game mechlab. If I did that it would be an unfair comparison as for example PPC can shoot twice in 5 seconds, and we'd have to show it's damage as double and that makes no sense at all. Showing a 5 second burst damage for each weapon instead of alpha will be even more confusing. PGI has tried to do what they can to make RAC weapons not look horrible on paper to players who don't want to do math by twisting the metrics, that's not something I will mimic :)

**Comment by sestrand** [comment]
Yea, I appreciate that.  I assume you account for the spin up, and maybe
spin down as well as the jam and jam duration.

for rac5s that did change from 6 to 8 sec before occurring, I am also
assuming that you are reading the files and including those values in your
damage calcs.

thanks for looking at it.

**Comment by sestrand** [comment]
oh, I guess I do have a question then,  for your RACs alpha are you using
the 5sec dmg value?  or are you using something more like 3 seconds (which
is a more realistic poke for the flamer / rac/ mg, in my opinion)

for the 5s and 10s burst calcs etc I assume you are using actual spin up
time and dmg per sec. (these are the ones I put the most faith in actually)

**Comment by LiSongMWO** [comment]
For alpha it takes one projectile from an RAC... you could argue it should be zero, because you can't really pop-tart with an RAC. On the other hand you could also argue that you pre-spin the weapon before your jump/peek so in that case it's correct within the LSML model. Really alpha doesn't make sense for RAC either way...

**Comment by sestrand** [comment]
true, but if you are using alpha for poptart then it would also be true
that it is invalid for lasers which also have a significant firing
duration.  in the laser case while it is a single short trigger pull it
definitely has a firing duration.

**Comment by LiSongMWO** [comment]
Ok, if you want to discuss changing the alpha behaviour, please open a separate bug for it so I can correctly track what code changes fix which bugs.

**Comment by sestrand** [comment]
heh.  sorry for leading this one off on a tangent.

**Comment by LiSongMWO** [comment]
@NonceCents I have replaced the mentions of cooldown with firing period which is more in line with what LSML actually computes for you.

See: https://github.com/EmilyBjoerk/lsml/wiki/Cooldowns
