### ISSUE TITLE
Update required to support structure changes brought in by 18 May 2021 Patch (1.4.241.0)

### ISSUE THREAD

**Issue by GidonsClaw** [lisongmechlab/lsml#747]
**LSML version:** 2.0.11
**Screen resolution:** 2560x1440
**Java version:** 8u301

**Steps to reproduce issue:**
1. Open LSML

**Actual result:**
Parse Error:

> java.io.IOException: Unable to load chassi configuration for [tdr-9sec]!
> 	at org.lisoft.lsml.model.database.gamedata.MwoDataReader.parseChassis(MwoDataReader.java:281)
> 	at org.lisoft.lsml.model.database.gamedata.MwoDataReader.parseGameFiles(MwoDataReader.java:177)
> 	at org.lisoft.lsml.view_fx.FXDatabaseProvider.updateDatabase(FXDatabaseProvider.java:282)
> 	at org.lisoft.lsml.view_fx.FXDatabaseProvider.loadDatabase(FXDatabaseProvider.java:257)
> 	at org.lisoft.lsml.view_fx.FXDatabaseProvider.getDatabase(FXDatabaseProvider.java:102)
> 	at org.lisoft.lsml.view_fx.LiSongMechLab.backgroundLoad(LiSongMechLab.java:259)
> 	at org.lisoft.lsml.view_fx.LiSongMechLab.access$000(LiSongMechLab.java:69)
> 	at org.lisoft.lsml.view_fx.LiSongMechLab$1.call(LiSongMechLab.java:211)
> 	at org.lisoft.lsml.view_fx.LiSongMechLab$1.call(LiSongMechLab.java:207)
> 	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: com.thoughtworks.xstream.converters.ConversionException: 
> ---- Debugging information ----
> cause-exception     : java.lang.NumberFormatException
> cause-message       : multiple points
> class               : org.lisoft.lsml.model.database.gamedata.helpers.MdfMovementTuning
> required-type       : org.lisoft.lsml.model.database.gamedata.helpers.MdfMovementTuning
> converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
> path                : /MechDefinition/MovementTuningConfiguration
> line number         : 167
> class[1]            : org.lisoft.lsml.model.database.gamedata.MdfMechDefinition
> required-type[1]    : org.lisoft.lsml.model.database.gamedata.MdfMechDefinition
> version             : 2.0.11
> -------------------------------
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:77)
> 	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:499)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:425)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
> 	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
> 	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
> 	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1487)
> 	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1467)
> 	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1347)
> 	at org.lisoft.lsml.model.database.gamedata.MdfMechDefinition.fromXml(MdfMechDefinition.java:67)
> 	at org.lisoft.lsml.model.database.gamedata.MwoDataReader.parseChassis(MwoDataReader.java:262)
> 	... 11 more
> Caused by: java.lang.NumberFormatException: multiple points
> 	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
> 	at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
> 	at java.lang.Double.parseDouble(Unknown Source)
> 	at java.lang.Double.valueOf(Unknown Source)
> 	at com.thoughtworks.xstream.converters.basic.DoubleConverter.fromString(DoubleConverter.java:27)
> 	at com.thoughtworks.xstream.converters.SingleValueConverterWrapper.fromString(SingleValueConverterWrapper.java:41)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:312)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
> 	... 27 more

**Expected result:**
No error, loading game specific information.

**Comment by sestrand** [comment]
I can confirm that this parse error is valid.  same results for me at startup.

**Comment by LiSongMWO** [comment]
Jesus PGI... what is this?! `TurnLerpLowRate="1..75"` another case of the data entry being absolutely broken... they have no validation of their XML at all...

How does that even pass their own parser? Who writes a parser that allows that?! Is the mech broken in game too?

**Comment by LiSongMWO** [comment]
Fixed in commit 6d3c2059577a80d2dfdc03f17f1c5c923ef32b13
