### ISSUE TITLE
[Question] Is the LSML database kept up to date with each patch?

### ISSUE THREAD

**Issue by MarHelmer** [lisongmechlab/lsml#749]
Sorry to create a GH issue for this, but I can't find another easy way to ask this, and I can't find any information on it.  Is LSML kept up to date with each patch?  I'd love to make this my primary fitting tool, but I don't want it to go the way of Smurfy and find that it's out of date.

**Comment by LiSongMWO** [comment]
LSML reads the game files directly and patches itself as soon as you update the game.
