### ISSUE TITLE
LSML somethimes forgets your garage file

### ISSUE THREAD

**Issue by LiSongMWO** [lisongmechlab/lsml#786]
**LSML version:** 2.0.15
**Java version:** 8u301

**Steps to reproduce issue:**
1. Unknown
1. Close LSML
1. Open LSML

**Actual result:**
LSML asks for the garage file

**Expected result:**
LSML doesn't forget which garage you had loaded.

Sometimes LSML forgets which garage you had loaded. This seems to have been introduced after the autosave feature was added. The problem is sporadic and there are no clear steps to reproduce it yet, making it hard to fix.

**Comment by GidonsClaw** [comment]
Also identified it changes the location of the default garage file to the auto save one every time it auto saves, and then after that re-opening the app causes it to ask the location of the garage file again.

**Comment by LiSongMWO** [comment]
Thanks, that'll make it easier for me to repro.
