### ISSUE TITLE
Unable to open builds in garage containing RL or add RL to a build without app hanging

### ISSUE THREAD

**Issue by GidonsClaw** [lisongmechlab/lsml#787]
**LSML version:** 2.0.15
**Screen resolution:** 2650x1440
**Java version:** 8u341

**Steps to reproduce issue:**
1. Open LSML
2. Click on existing build that contains RL's 
3. Application hangs on trying to open build

Alternative
1. Create a new build
2. Add a RL to build
3. Application hangs on trying to open build

**Actual result:**
Application hangs

**Expected result:**
Should either open and display build, or add RL without hanging.

![2022-08-17 08_41_00-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/16274203/184997616-c74f9025-8d1f-440b-a69f-6388b8e071ab.png)

**Comment by LiSongMWO** [comment]
Well that's awkward 😂
