### ISSUE TITLE
Smurfy no longer active

### ISSUE THREAD

**Issue by sestrand** [lisongmechlab/lsml#790]
**LSML version:** 2.0.15
**Screen resolution:** 3440x1440
**Java version:** 8uX

**Steps to reproduce issue:**
1. Open LSML
2. Click on sharing

**Actual result:**
Not really a problem, just no longer something that is useful in the interface.

**Expected result:**
LSML, probably doesnt need anything beyond copy and paste with MWOs import export codes.  The only other actively updated mechbuilder site that I am aware of is MechDB https://mech.nav-alpha.com.  MechDB can also import and export MWO codes, so nothing special needed for transfer to and from.  Smurfy was intermittent for a while last year, but seems gone now.  It had good tables... some of which I think now could be useful to display in LSML as MechDB has nothing like them either.

**Comment by LiSongMWO** [comment]
Let's keep this bug to delete the references to smurfy. Please file separate bugs as feature requests for tables that you would find useful.  :)

**Comment by LiSongMWO** [comment]
This was fixed by commit 281d89f73659ac421081650a1b3977c52eb5372e.
