### ISSUE TITLE
MRMs show as a jagged line in the weapon lab sand chart

### ISSUE THREAD

**Issue by sestrand** [lisongmechlab/lsml#792]
**LSML version:** 2.0.14
**Screen resolution:** 3440x1440
**Java version:** 8uX

**Steps to reproduce issue:**
1. Open LSML
2. Click on a mech with MRMs
3. Then on weapon lab

**Actual result:**
What should be a damage curve looks like a saw tooth over the range.

**Expected result:**
Should be smooth line with falloff somewhat like cannons.

**Comment by LiSongMWO** [comment]
I cannot reproduce this on 2.0.16:

![image](https://user-images.githubusercontent.com/5306929/188115287-56cb6f9e-4d36-4754-bf58-8c3913a2145d.png)

The curve is smooth, it's still affected by #789, but it's smooth. 

Can you please attach a screenshot?

**Comment by sestrand** [comment]
Mine is jagged with with other weapons (and perhaps as a sum of two MRMs?). 

![Screenshot 2022-09-02 084312](https://user-images.githubusercontent.com/46074852/188159595-218818ea-6521-4c17-a175-4982b1dc93d1.png)

**Comment by sestrand** [comment]
Figured it out.  Add a second MRM with different size.  That seems to be what causes this. 

![Screenshot 2022-09-02 084943](https://user-images.githubusercontent.com/46074852/188160630-c8988c53-1d20-411d-82a3-f442a6efa2ed.png)

**Comment by RosariusAU** [comment]
I believe this bug is common for all missile weapons if you have launchers of the same family but different size.
