### ISSUE TITLE
New quirk modifiers in MWO files give warning in LSML

### ISSUE THREAD

**Issue by sestrand** [lisongmechlab/lsml#803]
**LSML version:** 2.0.16
**Screen resolution:** 3440x1440
**Java version:** 8uX

**Steps to reproduce issue:**
1. Open LSML

**Actual result:**
> Task :run
Unknown selector: strategicstrikecapacity in quirk: strategicstrikecapacity_additive
Unknown selector: coolshotcapacity in quirk: coolshotcapacity_additive
Unknown selector: uavduration in quirk: uavduration_additive

**Expected result:**
this will modify the corresponding quirks.  no impact to the LSML calculations. These quirks are not weapon adjustments.

**Comment by cmdremily** [comment]
This is expected when new quirks are added. As long as there aren't quirks that LSML should take into account they can be ignored.

**Comment by LiSongMWO** [comment]
I fixed this but forgot which commit and forgot to tag this issue.
