### ISSUE TITLE
a few new warnings with may update for MWO.

### ISSUE THREAD

**Issue by sestrand** [lisongmechlab/lsml#820]
**LSML version:** 2.1.0
**Screen resolution:** 3440x1440
**Operating System:** Windows 11

**To Reproduce**
1. Open LSML in netbeans 
2. See warnings
Unknown selector: coolshotcooldown in quirk: coolshotcooldown_multiplier
Unknown spec: critdamage in quirk: missile_critdamage_multiplier
No such key found!: @qrk_clanheavymediumlaser_minheatpenaltylevel_add

**Comment by LiSongMWO** [comment]
All the new identifiers:

```
No such key found!: @qrk_ismediumlaserfamily_minheatpenaltylevel_add
Unknown selector: coolshotcooldown in quirk: coolshotcooldown_multiplier
Unknown spec: critdamage in quirk: missile_critdamage_multiplier
No such key found!: @qrk_clanheavymediumlaser_minheatpenaltylevel_add
Unknown selector: advancedzoom in quirk: advancedzoom_additive
Unknown selector: increasedarmor in quirk: increasedarmor_multiplier
Unknown selector: increasedstructure in quirk: increasedstructure_multiplier
Unknown selector: speedretention in quirk: speedretention_multiplier
Unknown selector: screenshake in quirk: screenshake_multiplier
Unknown selector: startupduration in quirk: startupduration_multiplier
Unknown selector: gaussextendedcharge in quirk: gaussextendedcharge_additive
No such key found!: @qrk_clanmediumlaserfamily_minheatpenaltylevel_add
```

**Comment by LiSongMWO** [comment]
Quite a few of these were caused by trial mechs getting pilot skills baked in via quirks.

I've disabled trial mechs from being parsed into LSML, it doesn't make sense as you can't build them in game anyway. I went ahead and added the quirks as recognized (but unused) by LSML if I ever get around to implementing skill trees.
