### ISSUE TITLE
Quirk warnings in July 23 update

### ISSUE THREAD

**Issue by sestrand** [lisongmechlab/lsml#821]
**LSML version:** 2.1.0
**Screen resolution:** 3440x1440
**Operating System:** Windows 11

**To Reproduce**
1. Open LSML in debugger
2. See warnings

**Actual result:**
Unknown selector: coolshotcooldown in quirk: coolshotcooldown_multiplier
Unknown spec: critdamage in quirk: missile_critdamage_multiplier
No such key found!: @qrk_clanheavymediumlaser_minheatpenaltylevel_add
No such key found!: @qrk_ismediumlaserfamily_minheatpenaltylevel_add
No such key found!: @qrk_clanmediumlaserfamily_minheatpenaltylevel_add

**Expected behavior**

**Additional context**
This set of new quirks (and new naming pattern) will impact the heat calculations.

**Comment by LiSongMWO** [comment]
Duplicate of #820.
